# Copyright 2017 TensorHub, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import absolute_import
from __future__ import division

import logging
import os
import re
import subprocess

from guild import namespace
from guild import resource
from guild import util
from guild.resolver import ResolutionError

log = logging.getLogger("guild")

RESOURCE_TERM = r"[a-zA-Z0-9_\-\.]+"

class DependencyError(Exception):
    pass

class ResolutionContext(object):

    def __init__(self, target_dir, opdef, resource_config):
        self.target_dir = target_dir
        self.opdef = opdef
        self.resource_config = resource_config

class Resource(object):

    def __init__(self, resdef, ctx):
        self.resdef = resdef
        self.ctx = ctx
        self._resource_config = self._init_resource_config()

    def _init_resource_config(self):
        for name, config in self.ctx.resource_config.items():
            if name in [self.resdef.fullname, self.resdef.name]:
                return config
        return None

    def resolve(self):
        log.info("Resolving %s resource", self.resdef.name)
        if not self.resdef.sources:
            log.warning(
                "%s resource does not define any sources",
                self.resdef.name)
        for source in self.resdef.sources:
            self._resolve_source(source)
        self._post_resolve()

    def _resolve_source(self, source):
        resolver = self.resdef.get_source_resolver(
            source, self._resource_config)
        if not resolver:
            raise DependencyError(
                "unsupported source '%s' in %s resource"
                % (source, self.resdef.name))
        try:
            source_paths = resolver.resolve()
        except ResolutionError as e:
            raise DependencyError(
                "could not resolve '%s' in %s resource: %s"
                % (source, self.resdef.name, e))
        except Exception as e:
            if log.getEffectiveLevel() <= logging.DEBUG:
                log.exception("dependency resolve")
            raise DependencyError(
                "could not resolve '%s' in %s resource: %s"
                % (source, self.resdef.name, e))
        else:
            for path in source_paths:
                self._link_to_source(path)

    def _link_to_source(self, source_path):
        source_path = util.strip_trailing_path(source_path)
        link = self._link_path(source_path)
        if os.path.exists(link):
            log.warning("source '%s' already exists, skipping link", link)
            return
        util.ensure_dir(os.path.dirname(link))
        log.debug("resolving source '%s' as link '%s'", source_path, link)
        os.symlink(source_path, link)

    def _link_path(self, source_path):
        basename = os.path.basename(source_path)
        res_path = self.resdef.path or ""
        if os.path.isabs(res_path):
            raise DependencyError(
                "invalid path '%s' in %s resource (path must be relative)"
                % (res_path, self.resdef.name))
        return os.path.join(self.ctx.target_dir, res_path, basename)

    def _post_resolve(self):
        if not self.resdef.post_resolve:
            return
        log.info(
            "Performing post resolve actions for %s resource",
            self.resdef.name)
        log.debug("post resolve: %s", self.resdef.post_resolve)
        try:
            subprocess.check_call(
                self.resdef.post_resolve,
                shell=True,
                cwd=self.ctx.target_dir)
        except subprocess.CalledProcessError as e:
            raise DependencyError(
                "error generated by post-resolve in %s resource: %s"
                % (self.resdef.name, e))

def _dep_desc(dep):
    return "%s:%s" % (dep.opdef.modeldef.name, dep.opdef.name)

def resolve(dependencies, ctx):
    for dep in dependencies:
        resource = _dependency_resource(dep.spec, ctx)
        resource.resolve()

def _dependency_resource(spec, ctx):
    resolved_spec = util.resolve_refs(spec, ctx.opdef.flag_values())
    res = util.find_apply(
        [_model_resource,
         _modelfile_resource,
         _packaged_resource],
        resolved_spec, ctx)
    if res:
        return res
    raise DependencyError(
        "invalid dependency '%s' in operation '%s'"
        % (resolved_spec, ctx.opdef.fullname))

def _model_resource(spec, ctx):
    m = re.match(r"(%s)$" % RESOURCE_TERM, spec)
    if m is None:
        return None
    res_name = m.group(1)
    return _modeldef_resource(ctx.opdef.modeldef, res_name, ctx)

def _modeldef_resource(modeldef, res_name, ctx):
    resdef = modeldef.get_resource(res_name)
    if resdef is None:
        raise DependencyError(
            "resource '%s' required by operation '%s' is not defined"
            % (res_name, ctx.opdef.fullname))
    return Resource(resdef, ctx)

def _modelfile_resource(spec, ctx):
    m = re.match(r"(%s):(%s)$" % (RESOURCE_TERM, RESOURCE_TERM), spec)
    if m is None:
        return None
    model_name = m.group(1)
    modeldef = ctx.opdef.modelfile.get(model_name)
    if modeldef is None:
        raise DependencyError(
            "model in resource '%s' required by operation "
            "'%s' is not defined"
            % (spec, ctx.opdef.fullname))
    res_name = m.group(2)
    return _modeldef_resource(modeldef, res_name, ctx)

def _packaged_resource(spec, ctx):
    m = re.match(r"(%s)/(%s)$" % (RESOURCE_TERM, RESOURCE_TERM), spec)
    if m is None:
        return None
    pkg_name = m.group(1)
    res_name = m.group(2)
    try:
        resources = list(resource.for_name(res_name))
    except LookupError:
        pass
    else:
        for res in resources:
            if namespace.apply_namespace(res.dist.project_name) == pkg_name:
                return Resource(res.resdef, ctx)
    raise DependencyError(
        "resource '%s' required by operation '%s' is not installed"
        % (spec, ctx.opdef.fullname))
