# Copyright 2017-2023 Posit Software, PBC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import click

from guild import click_util

from . import server_support


@click.command(name="view")
@server_support.host_and_port_options
@click.option(
    "-n", "--no-open", help="Don't open Guild View in a browser.", is_flag=True
)
@click_util.use_args
@click_util.render_doc
def view(args):
    """Run Guild View.

    Guild View is a runs management facility that lets you organize
    and analyze runs generated by Guild.
    """
    from . import view_impl

    view_impl.main(args)
