exports_files([
    "gpu-attrs",
    "nvidia-tools-check",
    "snapshot-project",
    "sys-attrs",
    "tensorflow-attrs",
    "tensorflow-check",
    "tensorflow-collector",
])

filegroup(
    name = "guild-exe",
    srcs = ["guild"],
    visibility = ["//visibility:public"],
)
