#!/bin/sh
_guild_env="$1"
if [ -z "$_guild_env" ]; then
    _guild_env=./env
fi

if [ ! -e "$_guild_env" ]; then
    echo "Guild environment $_guild_env does not exist"
    return 1
fi

if [ -e "$_guild_env/bin/activate" ]; then
    . "$_guild_env/bin/activate"
else
    "Could not find a Guild environment in $_guild_env"
    return 1
fi
