#!/usr/bin/env python

# Copyright 2017-2019 TensorHub, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

def main():
    sys.path.insert(0, _guild_import_path())
    import guild.main_bootstrap
    guild.main_bootstrap.main()

def _guild_import_path():
    script_home = os.path.dirname(__file__)
    return os.path.dirname(os.path.dirname(script_home))

if __name__ == '__main__':
    main()
