name: Check source code

on:
  ##- push
  - workflow_dispatch

jobs:
  checks:
    name: Pre-build checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint yapf
        pip install -r requirements.txt
        pip install -r guild/tests/requirements.txt

    - name: Run linter
      run: |
        python -m pylint setup.py guild --reports y

    - name: Check source code format
      if: ${{ success() || failure() }}
      run: |
        python -m yapf --diff -r setup.py tools.py guild examples
